sudo: required
services:
    - docker
    
before_install:
    - docker build -t djfwongyvr/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run djfwongyvr/react-test npm test -- --coverage
    
after_success:
    - docker build -t djfwongyvr/multi-client ./client
    - docker build -t djfwongyvr/multi-nginx ./nginx
    - docker build -t djfwongyvr/multi-server ./server
    - docker build -t djfwongyvr/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push djfwongyvr/multi-client
    - docker push djfwongyvr/multi-nginx
    - docker push djfwongyvr/multi-server
    - docker push djfwongyvr/multi-worker